[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Force browser to not use caching
  CACHE_CONTROL = "public, max-age=0, must-revalidate"

# Performance optimization - removes code splitting
[build.processing]
  skip_processing = false

[build.processing.js]
  bundle = true
  minify = true

[build.processing.css]
  bundle = true
  minify = true