[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Force browser to not use caching
  CACHE_CONTROL = "public, max-age=0, must-revalidate"

# Disable JS processing to avoid bundling issues
[build.processing]
  skip_processing = true

# If skip_processing is not enough, try controlling specific options
[build.processing.js]
  bundle = false
  minify = false

[build.processing.css]
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true